site_name: 'KubeOperator 文档'
site_url: 'https://kubeoperator.io/'
site_description: 'KubeOperator 文档'
site_author: 'wanghe'
google_analytics: ['UA-147297392-1', 'kubeoperator.io']

repo_name: 'KubeOperator'
repo_url: 'https://github.com/KubeOperator/KubeOperator'
edit_uri: ''

theme:
    name: 'material'
    logo: 'img/kubeoerator-white.png'
    favicon: 'img/KubeOperator-icon.png'
    language: 'zh'
    highlightjs: true
    palette:
        primary: 'deep orange'
        accent: 'red'
    feature:
        tabs: true
    hljs_languages:
        - yaml
        - django
    features:
        - search.suggest
        - search.highlight

nav:
    - 总体介绍: index.md
    - 主要概念: concept.md
    - 安装部署:
          - 产品部署架构: installation/deploy_architecture.md
          - 部署环境要求: installation/deploy_env.md
          - 在线安装: installation/online_installation.md
          - 离线安装: installation/offline_installation.md
    - 快速入门:
          - 系统设置: quick_start/system_settings.md
          - 集群规划:
                - 自动模式: quick_start/cluster_planning/automatic.md
                - 手动模式: quick_start/cluster_planning/manual.md
                - 公有云平台: quick_start/cluster_planning/public_cloud.md
          - 集群部署: quick_start/cluster_deployment.md
          - 集群导入: quick_start/cluster_import.md
          - 集群运营: quick_start/cluster_operation.md
    - 使用指南:
          - 项目管理: user_manual/project.md
          - 主机管理: user_manual/hosts.md
          - 部署计划: user_manual/plan.md
          - 版本管理: user_manual/version.md
          - 用户管理: user_manual/user_management.md
          - 系统设置: user_manual/system_management.md
    - 开发文档: dev/rest_api.md
    - 常见问题: faq.md
    - 教程:
          - 应用商店: guidelines/kubeapps.md
          - Argo CD: guidelines/argocd.md
    - 关于:
          - 更新说明: about/changelog.md
          - 联系我们: about/contact.md
    - 企业版试用: enterprise.md

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: True
        linenums: False
    - toc:
        permalink: True
    - footnotes
    - attr_list
    - def_list
    - tables
    - abbr
    - md_in_html
    - pymdownx.extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.tabbed
    - pymdownx.betterem
    - pymdownx.superfences
    - pymdownx.progressbar
    - pymdownx.tasklist:
        custom_checkbox: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KubeOperator

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2014-2020 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>

plugins:
    - search
